### ISSUE TITLE
Ny lenkeboks på Skriv til oss

### ISSUE THREAD

**Issue by ojnybo** [navikt/pb-kontakt-oss#257]
Ny lenkeboks på STO. Legges nest nederst i oversikten, over den inaktive Økonomisk sosialhjelp-boksen

Tekst:
**Får ikke reist til Norge**
Spørsmål til hvordan innreisereglene påvirker dine rettigheter eller ytelser hos NAV.

**Can't travel to Norway**
Questions about how the travel restrictions affect your rights or benefits at NAV. The form is in Norwegian.

URL
http://mininnboks-q1.nav.no/sporsmal/skriv/OVRG
http://mininnboks.nav.no/sporsmal/skriv/OVRG

**Comment by Laier68** [comment]
****Tatt en kjapp test av saken i Q1**

1) Gå uinnlogget mot lenke boksen - [ ] OK
    Rutes ID-Porten med kun nivi 4 innlogging
    Rutes etter innlogging inn på https://mininnboks.nav.no/sporsmal/skriv/OVRG
![image](https://user-images.githubusercontent.com/60879532/106350434-a2928700-62d5-11eb-8c63-4cd605a2145f.png)**
