### ISSUE TITLE
Forberede flytting av kontakt-oss forside til Enonic XP

### ISSUE THREAD

**Issue by anders-nom** [navikt/pb-kontakt-oss#286]
- Fjern nais-ingresser som skal overtas av XP
- Fjern kode/innhold i appen som ikke vil være i bruk lengre

**Comment by Laier68** [comment]
Tatt en kjapp kompatibiltets test.
- [ ] Laptop vin 10  / Chrome-Firefox-Edge 
- [ ] Mac / Big sur / Cataline - Safari
- [ ] Mobil IOS 14 13 12 11 10 / Safari og Chrome
- [ ] Android 10 / 9 Chrome
 
 * Litt lurvete visning i IOS 9 av de ekspanderbare menyene men det er en så gml versjon så må være greit nok.

**Comment by Laier68** [comment]
Verifisert OK i prod etter prod.setting.
Fikk feedback fra Tom G. at overgang STO fra Innboks feilet, manglet en redirect og ble fikset på umiddelbart
